### ISSUE TITLE
Set up JS

### ISSUE THREAD

**Issue by BMArsenault** [BMArsenault/proj-01-HikeSpot#4]
- [x] Get search button to save locations into local storage
- [x] Transfers search text to maps and weather API
- [x] Display map of places to hike in area of city searched - as well as recent searches (?)

If there's anything I'm missing, feel free to chime in.

**Comment by BMArsenault** [comment]
Looked into more map api's.  Looks like the mapbox that Ron initially sent out is probably going to be the best map api but we just need to figure out a way to specifically search parks when we type in a city.

**Comment by Christian55diaz** [comment]
I think would work for saving the data in the local storage (var input = document.getElementById('saveServer').value;
localStorage.setItem('server', input);) and to get the text back we would use (document.getElementById('saveServer').value = localStorage.getItem('server');)
